### ISSUE TITLE
pip installation error

### ISSUE THREAD

**Issue by Tolga28A** [tofunlp/sister#48]
pip installation gives long lines of errors on the command prompt having this piece:

  ERROR: Failed building wheel for fasttext
  Running setup.py clean for fasttext
Failed to build fasttext
Installing collected packages: fasttext, sister
    Running setup.py install for fasttext ... error
    ERROR: Command errored out with exit status 1:

Any help?

**Comment by sobamchan** [comment]
@Tolga28A 
Thanks for your report, I will look into it.
Hopefully, I will get back to you within a day.

**Comment by sobamchan** [comment]
@Tolga28A 
Hi, I could not reproduce your error.

my environment below
- macos catalina
- pyenv, pyenv-virtualenv
- python version 3.8.1

According to the error message you posted, it seems like there is a problem to install [fasttext](https://github.com/facebookresearch/fastText/tree/master/python#fasttext-), one of sister's dependencies.

You can probably try to [install fasttext](https://github.com/facebookresearch/fastText/tree/master/python#fasttext-) separately to understand the trouble better.

If you can not install it, it may be caused by your python environment.
(There is no problems on the installation of fasttext at my laptop)  .

**Comment by Tolga28A** [comment]
Hi, let me check fasttext installation. Thank you so much for your help!

**Comment by sobamchan** [comment]
I hope it works out, and you can enjoy this lib!
